language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      service: mysql
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      addons:
        apt:
          packages:
            - mariadb-server
            - libmariadbclient-dev
    - os: osx
      osx_image: xcode7.2
      before_install:
        - brew install mariadb
        - mysql.server start
      latex: false
    - os: osx
      osx_image: xcode7.2
      before_install:
        - brew install mysql mysql-connector-c
        - mysql.server start
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true
      r_check_args: '--no-tests'

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'billy'@'localhost' IDENTIFIED BY 'supersecret';" -uroot
  - printf "[rs-dbi]\nusername=billy\npassword=supersecret\n" > ~/.my.cnf

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
