# Info:
# https://docs.travis-ci.com/user/languages/r/
# https://docs.travis-ci.com/user/database-setup/#MySQL

language: r
cache: packages
sudo: false

services:
  - mysql
addons:
  apt:
    packages:
      - libmysqlclient-dev

#r_check_revdep: true

r_github_packages:
  - rstats-db/DBI
  - rstats-db/DBItest@production

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;" -uroot
