language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode7.2
      brew_packages: mariadb-connector-c
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true

addons:
  mariadb
  apt:
    packages:
      - libmariadbclient-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - mysql -e "CREATE USER 'billy'@'localhost' IDENTIFIED BY 'supersecret';"
  - printf "[rs-dbi]\nusername=billy\npassword=supersecret\n" > ~/.my.cnf

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
